#!/usr/bin/env bash
# inserts custom http header into server block
sudo apt-get -y update
if sudo apt-get -y install nginx; then
	PLACE=$(grep -m 1 'root' /etc/nginx/sites-available/default | cut -d ' ' -f2 | tr -d ';')
	sudo bash -c 'echo "Holberton School" > "'"$PLACE"'/index.html"'
	new="location ~ '/redirect_me(?=\/|)' {\n\t\treturn 301 https://qz.com/;\n\t}"
	sudo sed -i "/^\tserver_name localhost;$/a \\\n\\t$new" /etc/nginx/sites-available/default
	new="\t\terror_page 404 @my404;"
	sudo sed -i "/^\tlocation \/ {$/a \\$new" /etc/nginx/sites-available/default
	new="location @my404 {\n\t\tdefault_type text/html;\n\t\treturn 404 \"Ceci n'est pas une page\\\n\\\n\";\n\t}"
	sudo sed -i "/^\tserver_name localhost;$/a \\\n\\t$new" /etc/nginx/sites-available/default
	sed -E -i '\|^server\s*\{$|a\\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default
fi
service nginx restart
