#!/usr/bin/env bash
# installs and configures haproxy
apt-get -y update
if sudo apt-get -y install haproxy; then
	sed -i 's/^ENABLED=0/ENABLED=1/' /etc/default/haproxy
	cp /etc/haproxy/haproxy.cfg{,.original}
	ADD='\n
	frontend http_front\n
		\tbind *:80\n
		\tdefault_backend http_back\n
	\n
	backend http_back\n
		\tbalance roundrobin\n
		\tserver 361-web-01 35.237.72.232:80 check\n
   		\tserver 361-web-02 34.73.16.66:80 check\n
	'
	echo -en "$ADD" >> /etc/haproxy/haproxy.cfg
	/etc/init.d/haproxy restart
fi		
