#!/usr/bin/env bash
# installs and configures haproxy
apt-get -y update
if sudo apt-get -y install haproxy; then
	sed -i 's/^ENABLED=0/ENABLED=1/' /etc/default/haproxy
	cp /etc/haproxy/haproxy.cfg{,.original}
	ADD='
frontend http_front
	bind *:80
	default_backend http_back

backend http_back
	balance roundrobin
	server 361-web-01 35.237.72.232:80 check
   	server 361-web-02 34.73.16.66:80 check
'
	echo -en "$ADD" >> /etc/haproxy/haproxy.cfg
	/etc/init.d/haproxy restart
fi		
