#!/usr/bin/env bash
# FizzBuzz: 2bash 2furious
counter=1
on=0
while [ $counter -le 100 ]
do	
	if [ $(( $counter % 3 )) -eq 0 ]; then
		echo -n "Fizz"
		on=1
	fi
	if [ $(( $counter % 5 )) -eq 0 ]; then
		echo -n "Buzz"
		on=1
	fi
	if [ $on -eq 0 ]; then
		echo -n "$counter"
	fi
	echo ""
	on=0
	((counter++))
done
