#!/usr/bin/env bash
# Displays "Holberton School" ten times with a while loop
counter=1
while [ $counter -le 10 ]
do
	echo "Holberton School"
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	fi
	((counter++))
done
