#!/usr/bin/env bash
# Displays bad and good numbers in a count
counter=1
while [ $counter -le 10 ]
do	
	if [ $counter -eq 4 ]; then
		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((counter++))
done
