#!/usr/bin/env bash
# Tests file existence
x="holbertonschool"
if [ -e $x ]; then
	echo "$x file exists"
	if [ -s $x ]; then
		echo "$x file is not empty"
	else
		echo "$x file is empty"
	fi
	if [ -f $x ]; then
		echo "$x is a regular file"
	fi
else
	echo "$x file does not exist"
fi
