#!/usr/bin/env bash
# install nginx on server, set up redirect, and custom 404
sudo apt-get -y update
if sudo apt-get -y install nginx; then
	PLACE=$(grep -m 1 'root' /etc/nginx/sites-enabled/default | cut -d ' ' -f2 | tr -d ';')
	sudo bash -c 'echo "Holberton School" > "'"$PLACE"'/index.html"'
	new="location ~ '/redirect_me(?=\/|)' {\n\t\treturn 301 https://qz.com/;\n\t}"
	sudo sed -i "/^\tserver_name localhost;$/a \\\n\\t$new" /etc/nginx/sites-enabled/default
	new="\t\terror_page 404 @my404;"
	sudo sed -i "/^\tlocation \/ {$/a \\$new" /etc/nginx/sites-enabled/default
	new="location @my404 {\n\t\tdefault_type text/html;\n\t\treturn 404 \"Ceci n'est pas une page\\\n\\\n\";\n\t}"
	sudo sed -i "/^\tserver_name localhost;$/a \\\n\\t$new" /etc/nginx/sites-enabled/default
	sudo service nginx restart
fi
